### ISSUE TITLE
error[E0609]: no field `poll` on type `poll_app::CreateBumps`

### ISSUE THREAD

**Issue by hnlisf** [lostintime101/seahorse_solana_programs#1]
When I studied your second Seahorse Solana program, copied your code, and executed the build instruction, the following error occurred like this:

```
Building...
warning: unused macro definition: `Loaded`
 --> src/lib.rs:6:3876
  |
6 | ... ; fn store (loaded : Self :: Loaded) -> Self ; } macro_rules ! Loaded { ($ name : ty) => { < $ name as Loadable > :: Loaded } } pub (...
  |                                                                    ^^^^^^
  |
  = note: `#[warn(unused_macros)]` on by default
 
error[E0609]: no field `poll` on type `poll_app::CreateBumps`
 --> src/lib.rs:6:5286
  |
6 | ...nts . poll , & programs_map) , bump : Some (ctx . bumps . poll) } ; create_handler (user . clone () , poll . clone ()) ; dot :: progra...
  |                                                              ^^^^ unknown field
 
warning: `poll_app` (lib) generated 1 warning
error: could not compile `poll_app` due to previous error; 1 warning emitted
```

I tried to find a solution on the Internet, but couldn't find one. I hope you can give me some advice. Thank you.

**Comment by hnlisf** [comment]
I've fixed this issue and modified the code as follows:
```

@instruction
def create(user: Signer, poll: Empty[Poll]):
    poll = poll.init(payer=user,seeds=['Poll',user])

```

**Comment by lostintime101** [comment]
thanks hnlisf, 
yes this seems to be coming up as an issue now, 
previously it was fine to initialize without seeds,
feel free to put in a PR to change the program

**Comment by elaemmanuel** [comment]
You still get an error while testing..

class Poll(Account):
  ethereum: u64
  solana: u64
  polygon: u64

@instruction
def create(poll: Empty[Poll], user: Signer ):
  poll = poll.init(
    payer = user,
    seeds =['Poll', user]
  )


@instruction
def vote(user: Signer, poll: Poll, voting_op: str):
  if voting_op == "eth":
    poll.ethereum += 1
  elif voting_op == "sol":
    poll.solana += 1
  elif voting_op == "pol":
    poll.polygon += 1
  else:
    print("Candidate does not exist")



❌  Test 'create' failed: 
Instruction index: 0
Reason: A seeds constraint was violated.

How did you fix that

**Comment by elaemmanuel** [comment]
got an error while testing..

Testing 'create'...
❌  Test 'create' failed: 
Instruction index: 0
Reason: A seeds constraint was violated.

here is the code 

class Poll(Account):
  ethereum: u64
  solana: u64
  polygon: u64

@instruction
def create(poll: Empty[Poll], user: Signer ):
  poll = poll.init(
    payer = user,
    seeds =['Poll', user]
  )


@instruction
def vote(user: Signer, poll: Poll, voting_op: str):
  if voting_op == "eth":
    poll.ethereum += 1
  elif voting_op == "sol":
    poll.solana += 1
  elif voting_op == "pol":
    poll.polygon += 1
  else:
    print("Candidate does not exist")

Using solana playground....

how can i fix this ?
